# Generated by Django 2.2.16 on 2022-06-06 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
