# Generated by Django 2.2.16 on 2022-06-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20220616_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(max_length=5500000, upload_to='recipes/images', verbose_name='Обложка'),
        ),
    ]
