# Generated by Django 2.2.16 on 2022-06-12 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20220612_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
    ]
