# Generated by Django 2.2.16 on 2022-06-04 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribition',
            name='author',
        ),
        migrations.AddField(
            model_name='subscribition',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='subscribitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='subscribition',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='subscribition',
            name='subscriber',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
