# Generated by Django 2.2.16 on 2022-06-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220606_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='goods',
            new_name='recipes',
        ),
    ]
