# Generated by Django 2.2.16 on 2022-06-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220606_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='recipes',
            field=models.ManyToManyField(blank=True, null=True, related_name='shopping_carts', to='food.Ingridient'),
        ),
    ]
