# Generated by Django 2.2.16 on 2022-06-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220606_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='shopping_carts', to='food.Recipe'),
        ),
    ]
